# Generated by Django 5.2.14 on 2026-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('input_text', models.TextField(verbose_name='Введённый текст')),
                ('detected', models.CharField(max_length=100, verbose_name='Определённый язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Лог определения языка',
                'verbose_name_plural': 'Логи определения языков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FindLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('query', models.CharField(max_length=200, verbose_name='Запрос')),
                ('found', models.BooleanField(verbose_name='Найден?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Лог поиска языка',
                'verbose_name_plural': 'Логи поиска языков',
                'ordering': ['-created_at'],
            },
        ),
    ]
