# Generated by Django 5.2.14 on 2026-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='findlog',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
